version: "3.9"
services:
  camcode-api:
    build:
      context: ./server
      dockerfile: ./Dockerfile-prod
    ports:
      - "8081:8081"

  camcode-client:
    build:
      context: ./camcode-client
      dockerfile: ./Dockerfile-prod
    ports:
      - '443:443'
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: ./Dockerfile-prod
    ports:
      - "3443:443"
#docker-compose -f docker-compose-prod.yml up --build
